name: An idea
description: Something Chatwire could do, or do better
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like Chatwire to do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: What would it help you with?
